print("Welcome to Badminton court")
print("\n\nสวัสดีค่ะ กรอกชื่อและเวลาที่ยืม")
name = input("ชื่อ")
time = input("เวลา")
quantity = input("จำนวนอุปกรณ์")
print("\n\nยินดีต้อนรับ คุณ", name)
print("เวลา ", time, "จำนวนอุปกรณ์", quantity)
print("\n\nขอบคุณที่มาใช้บริการที่สนามแบตมินตันของเรา")