# -*- coding: utf-8 -*-
"""Pingpong_39_pythonipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1itghbV_Wvi9meh1v3TOdO4Yh767BhXW9
"""

def calculate_volume(width, length, height):
    return (width * length * height) / 1_000_000


width = float(input("Enter width (cm): "))
length = float(input("Enter length (cm): "))
height = float(input("Enter height (cm): "))


if width == 30 and length == 50 and height == 40:
    volume = calculate_volume(30, 50, 40)
elif width == 40 and length == 40 and height == 40:
    volume = calculate_volume(40, 40, 40)
elif width == 50 and length == 60 and height == 80:
    volume = calculate_volume(50, 60, 80)
else:
    volume = calculate_volume(width, length, height)


print(f"Volume: {volume:.6f} cubic meters")